/**
 * Images.
 *
 * The `kind` split is what makes the migration from the current site
 * non-destructive. Today every photograph on the site is a hot-linked Unsplash
 * or Pexels URL, built by web/lib/images.ts from a provider id plus the crop
 * the layout wants. Those become `kind: "remote"` rows that keep the provider
 * id, so the exact same URLs are still generated and the site renders
 * byte-identically on the day the database goes live — no downloads, no
 * re-encoding, no visual regression.
 *
 * Uploads through the dashboard are `kind: "local"`: files on the Railway
 * volume, resized by sharp at write time.
 *
 * A remote row can be "adopted" into a local one later, which is how real site
 * photography will replace the stock placeholders without touching content.
 */

import {
  index,
  mysqlTable,
  smallint,
  tinyint,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";
import { relations } from "drizzle-orm";

import {
  activeCopyOf,
  actors,
  bigintId,
  pk,
  softDelete,
  timestamps,
} from "./_base";
import { companies } from "./tenancy";

export const media = mysqlTable(
  "media",
  {
    id: pk(),
    companyId: bigintId("company_id")
      .notNull()
      .references(() => companies.id),

    kind: varchar("kind", { length: 8 }).notNull().$type<"local" | "remote">(),

    /** local — path under MEDIA_ROOT, namespaced by company:
        media/<company_id>/<yyyy>/<nanoid>. Variants live inside as <width>.webp.
        For seeded remote rows this holds the old ImageKey ("svc-pile-testing"),
        which gives every row a stable natural key.

        That key is what makes the seed idempotent: without a unique index here,
        re-running the seed inserts a second copy of all 32 photographs instead
        of updating them, and every content row keeps pointing at the original
        while the duplicates accumulate invisibly. */
    storageKey: varchar("storage_key", { length: 255 }),
    storageKeyActive: activeCopyOf("storage_key", 255),

    /** remote — the provider's default-crop URL, plus the pieces needed to
        rebuild any other crop. Keeping `provider` and `providerId` (rather than
        just the URL) is what lets mediaUrl(m, w, h) reproduce today's
        imageAt() behaviour instead of stretching a fixed-size image. */
    remoteUrl: varchar("remote_url", { length: 600 }),
    provider: varchar("provider", { length: 16 }).$type<"unsplash" | "pexels">(),
    providerId: varchar("provider_id", { length: 64 }),

    mime: varchar("mime", { length: 40 }),
    width: smallint("width", { unsigned: true }),
    height: smallint("height", { unsigned: true }),
    bytes: bigintId("bytes"),

    /** Tiny base64 WebP for next/image's blur placeholder. Generated by sharp
        on upload; null for remote rows, which fall back to no placeholder. */
    blurDataUrl: varchar("blur_data_url", { length: 2048 }),

    /** Required by the dashboard's picker before an image can be attached.
        Nullable at the DB level only because seeded stock photos start without
        it; the API rejects empty alt on any user-facing write. */
    alt: varchar("alt", { length: 300 }).notNull().default(""),
    title: varchar("title", { length: 200 }),

    /** Focal point as percentages, driving CSS object-position. This replaces
        the hand-tuned per-slot crops that web/lib/images.ts currently encodes
        in comments — the editor clicks the subject instead of an engineer
        picking pixel dimensions. */
    focalX: tinyint("focal_x").notNull().default(50),
    focalY: tinyint("focal_y").notNull().default(50),

    ...timestamps,
    ...softDelete,
    ...actors,
  },
  (t) => [
    uniqueIndex("uq_media_storage_key_active").on(t.companyId, t.storageKeyActive),
    index("ix_media_company").on(t.companyId, t.isDeleted, t.id),
    index("ix_media_kind").on(t.companyId, t.kind, t.isDeleted),
  ]
);

export const mediaRelations = relations(media, ({ one }) => ({
  company: one(companies, {
    fields: [media.companyId],
    references: [companies.id],
  }),
}));
